### ISSUE TITLE
Root Builder Potential Feature Request

### ISSUE THREAD

**Issue by ComatoseHub** [Kezyma/ModOrganizer-Plugins#32]
Is there a way to bypass the filtering of a specific folder or files in the data folder to have it loaded from the beginning?
My example is the New Vegas Heap Replacer there are files that need to be there at load time.

**Comment by Kezyma** [comment]
That's already possible with customised exclusions.

I'd only install NVHR if you're absolutely sure you need it as it often causes stutter and crashes in my experience.
